### ISSUE TITLE
bad luck for 100 years!

### ISSUE THREAD

**Issue by rainyskye** [pmnlla/robot-arm-test#3]
163 errors, 782 warnings, no compilation!

**Comment by pmnlla** [comment]
skye please that's not the only thing wrong with this code 😭 all my pwm logic is in fn main i need to write an interrupt routine to replace it with

**Comment by pmnlla** [comment]
you're lucky this is a school project otherwise this issue would go downhill VERY FAST.

FYI to whoever actually bothers to try to compile this: there's a lot wrong with the code. a lot of it needs to be rewritten to support 20ms PWM periods, which it currently does not. Thanks to Atmel. 🖕

it also needs a better command parser, and lighter implementations of trigonometric functions. oh, and a complete removal of half the empty files. and to split up a lot of the code too. assuming i can make this fit in 32kb.
